// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.API.Data;

#nullable disable

namespace kt6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240506064133_ИмяМиграциука")]
    partial class ИмяМиграциука
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("kt6.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("kt6.Models.Project", b =>
                {
                    b.Property<int>("ID_проекта")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Дата_начала")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Дата_окончания")
                        .HasColumnType("TEXT");

                    b.Property<string>("Название_проекта")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Статус")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_проекта");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
